package net.applee.gdlevelapi.objects.enums;

public enum OfficialMusic {
	STEREO_MADNESS,
	BACK_ON_TRACK,
	POLARGEIST,
	DRY_OUT,
	BASE_AFTER_BASE,
	CANT_LET_GO,
	JUMPER,
	TIME_MACHINE,
	CYCLES,
	X_STEP,
	CLUTTERFUNK,
	THEORY_OF_EVERYTHING,
	ELECTROMAN_ADVENTURES,
	CLUBSTEP,
	ELECTRODYNAMIX,
	HEXAGON_FORCE,
	BLAST_PROCESSING,
	THEORY_OF_EVERYTHING_2,
	GEOMETRICAL_DOMINATOR,
	DEADLOCKED,
	FINGERDASH,
	DASH
}
